name: Build Actions for DuinoLed

on: [push, pull_request]

# DuinoLed has no source files that are unottest-able
#
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Arduino/libraries/DuinoLed
    steps:

    # Checkout the repository

    - name: Checkout DuinoLed
      uses: actions/checkout@v4
      with:
        path: Arduino/libraries/DuinoLed

    - name: Checkout DuinoUtil
      uses: actions/checkout@v4
      with:
        repository: dhylands/DuinoUtil
        path: Arduino/libraries/DuinoUtil

    - name: Checkout DuinoMakefile
      uses: actions/checkout@v4
      with:
        repository: dhylands/DuinoMakefile
        path: Arduino/libraries/DuinoMakefile

    - name: Test Code Formatting
      run: make BOARD=pico test-style

    - name: Install cpplint
      run: sudo apt install -y cpplint
      working-directory: .

    - name: Run Linter
      run: make BOARD=pico lint

    - name: Install doxygen
      run: sudo apt install -y doxygen graphviz
      working-directory: .

    - name: Test that docs passes
      run: make BOARD=pico docs

    - name: Install arduino-cli and rp2040 support
      run: make BOARD=pico install-cli

    - name: Dump arduino-cli config
      run: ~/bin/arduino-cli config dump

    - name: Install Arduino library dependencies
      run: make BOARD=pico install-deps

    - name: Ensure HeartBeat.ino compiles
      run: make -C examples/Heartbeat BOARD=pico compile

    - name: Ensure HeartBeat_NeoPixel.ino compiles
      run: make -C examples/Heartbeat_NeoPixel BOARD=zero compile
